language: go
sudo: false
go:
  - 1.11.x
env:
  - GO111MODULE=on

install:
  - go mod download
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"

go_import_path: github.com/go-kira/kira

script:
  - go test ./tests